// Mocks generated by Mockito 5.4.5 from annotations
// in tdd_clean/test/features/news/domain/usecase/get_news_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tdd_clean/core/error/failures.dart' as _i5;
import 'package:tdd_clean/features/news/domain/news_entity.dart' as _i6;
import 'package:tdd_clean/features/news/domain/news_repo.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NewsRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNewsRepo extends _i1.Mock implements _i3.NewsRepo {
  MockNewsRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.NewsEntity>> getQueryNews(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getQueryNews, [query]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.NewsEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.NewsEntity>(
                    this,
                    Invocation.method(#getQueryNews, [query]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.NewsEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.NewsEntity>> getCountryNews(
    String? country,
    String? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCountryNews, [country, category]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.NewsEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.NewsEntity>(
                    this,
                    Invocation.method(#getCountryNews, [country, category]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.NewsEntity>>);
}
